name: Docker lint check

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x /bin/hadolint
      - uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
          lint: 'hadolint'