name: Docker lint check

on: [push]

jobs:
  lint:

    runs-on: hadolint/hadolint:latest-debian

    steps:
      - uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
          lint: 'hadolint'