name: Docker lint check

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo wget -q -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint
      - name: Analysing the Dockerfile
        run: | 
          ls -la ../
          /bin/hadolint -V ../Dockerfile